#!/bin/sh

rm /usr/script/DEL/plugin0.sh
rm /usr/script/DEL/plugin1.sh
rm /usr/script/DEL/plugin2.sh
rm /usr/script/DEL/plugin3.sh
rm /usr/script/DEL/plugin4.sh
rm /usr/script/DEL/plugin5.sh
rm /usr/script/DEL/plugin6.sh
rm /usr/script/DEL/plugin7.sh
rm /usr/script/DEL/plugin8.sh
rm /usr/script/DEL/plugin9.sh
rm /usr/script/DEL/plugin10.sh
rm /usr/script/DEL/plugin11.sh
rm /usr/script/DEL/plugin12.sh
rm /usr/script/DEL/plugin13.sh
rm /usr/script/DEL/plugin15.sh
rm /usr/script/DEL/plugin16.sh
rm /usr/script/DEL/plugin17.sh
rm /usr/script/DEL/plugin18.sh
rm /usr/script/DEL/plugin19.sh
rm /usr/script/DEL/plugin20.sh
rm /usr/script/DEL/plugin21.sh
rm /usr/script/DEL/plugin22.sh
rm /usr/script/DEL/plugin24.sh
rm /usr/script/DEL/plugin25.sh
rm /usr/script/DEL/plugin26.sh
rm /usr/script/DEL/plugin27.sh
rm /usr/script/DEL/plugin28.sh
rm /usr/script/DEL/plugin29.sh
rm /usr/script/DEL/plugin30.sh
rm /usr/script/DEL/plugin31.sh
rm /usr/script/DEL/plugin32.sh
rm /usr/script/DEL/plugin33.sh
rm /usr/script/DEL/plugin34.sh
rm /usr/script/DEL/plugin35.sh
rm /usr/script/DEL/plugin36.sh
rm /usr/bin/ebox
rm /usr/script/hdbox.sh
rm /usr/script/nova.sh
rm /usr/script/dualipa.sh
rm /usr/script/halsey.sh
rm /usr/script/scooter.sh
rm /usr/script/musicBoxHitsOLD.sh
rm /usr/script/SkTonline1.sh
rm /usr/script/SkTonline2.sh
rm /usr/script/SkTonlineCONV1.sh
rm /usr/script/SkTonlineCONV2.sh
rm /usr/script/DokumentyCONV.sh
rm /usr/script/KoncertyCONV.sh
rm /usr/script/KresleneCONV.sh
rm /usr/script/SerialyCONV.sh
rm /usr/script/feed.sh
rm /usr/script/cpu.sh
rm /usr/script/osON.sh
rm /usr/script/osFF.sh
rm /usr/script/delCONV.sh
rm /usr/script/PinkCONV.sh
rm /usr/script/FilmCONV.sh
rm /usr/script/PohadkyCONV.sh
rm /usr/script/RusCONV.sh
rm /usr/script/GreeceCONV.sh
rm /usr/script/xxxCONV.sh
rm /usr/script/AdultCONV.sh
rm /usr/script/CzechCONV.sh
rm /usr/script/IpCONV.sh
rm /usr/script/RomaniaCONV.sh
rm /usr/script/SmartCONV.sh
rm /usr/script/BeinSportCONV.sh
rm /usr/script/textMAL.sh
rm /usr/script/textVEL.sh
rm /usr/script/Plugin-Update.sh
rm /usr/script/zobrazCFGactual.sh
rm /usr/script/infoOFF.sh
rm /usr/script/cfgOFF.sh
rm /usr/script/cfgON.sh
rm /usr/script/CFG.sh
rm /usr/script/photo.sh
rm /usr/script/photoSTART.sh
rm /usr/script/SerUpdate1.sh
rm /usr/script/SerUpdate2.sh
rm /usr/script/SerUpdate3.sh
rm /usr/script/SerUpdate4.sh
rm /usr/script/SerUpdate5.sh
rm /usr/script/SerUpdate6.sh
rm /usr/script/SerUpdate7.sh
rm /usr/script/SerUpdate8.sh
rm /usr/script/SerUpdate9.sh
rm /usr/script/SerUpdate10.sh
rm /usr/script/SerUpdate11.sh
rm /usr/script/SerUpdate12.sh
rm /usr/script/SerUpdate13.sh
rm /usr/script/seznam1.sh
rm /usr/script/seznam2.sh
rm /usr/script/seznam3.sh
rm /usr/script/seznam4.sh
rm /usr/script/seznam5.sh
rm /usr/script/spojenisez.sh
rm /usr/script/update.sh
rm /usr/script/convON.sh
rm /usr/script/convOFF.sh
rm /usr/script/restartsamostat.sh
rm /usr/script/restart.sh
rm /usr/script/restartON.sh
rm /usr/script/restartOFF.sh
rm /usr/script/dataXON.sh
rm /usr/script/dataXOFF.sh
rm /usr/script/saveCFG.sh
rm /usr/script/navratCFG.sh
rm /usr/script/zobrazCFG.sh
rm /usr/script/tiche.sh
rm /usr/script/tiche1.sh
rm /usr/script/tichestart1x.sh
rm /usr/script/tichestart1.sh
rm /usr/script/tichestart2.sh
rm /usr/script/tichestart3.sh
rm /usr/script/ajktv.sh
rm /usr/script/clinespot.sh
rm /usr/script/cccamboss.sh
rm /usr/script/cccamgoal.sh
rm /usr/script/cccamlux.sh
rm /usr/script/cccamlive.sh
rm /usr/script/satunivers.sh
rm /usr/script/cccamsiptv.sh
rm /usr/script/cccamon.sh
rm /usr/script/paksat.sh
rm /usr/script/cccamlion.sh
rm /usr/script/cccamingo.sh
rm /usr/script/freecamtv2.sh
rm /usr/script/freecamtv3.sh
rm /usr/script/iptvpremiums.sh
rm /usr/script/cccamnet.sh
rm /usr/script/pakdosti.sh
rm /usr/script/iptvkiller.sh
rm /usr/script/premium-cccam.sh
rm /usr/script/cccammania.sh
rm /usr/script/cccamstore.sh
rm /usr/script/cccam-full.sh
rm /usr/script/linux24.sh
rm /usr/script/webtechdz.sh
rm /usr/script/satcccam.sh
rm /usr/script/sat-gold.sh
rm /usr/script/urliptv.sh
rm /usr/script/cccameurop.sh
rm /usr/script/cccamiptv.sh
rm /usr/script/cccamiptvs.sh
rm /usr/script/cccamsupreme.sh
rm /usr/script/firecccam.sh
rm /usr/script/cccamprime.sh
rm /usr/script/mycccam.sh
rm /usr/script/spotline.sh
rm /usr/script/cccams.sh
rm /usr/script/thecccam.sh
rm /usr/script/cccamax.sh
rm /usr/script/OSCAMconv.sh
rm /usr/script/rychloCONV.sh
rm /usr/script/saveOSCAM.sh
rm /usr/script/zobrazOSCAM.sh
rm /usr/script/navratOSCAM.sh
rm /usr/script/zobrazOSCAMactual.sh
rm /usr/script/plugin1.sh
rm /usr/script/plugin2.sh
rm /usr/script/xxxfilmsUDPCONV.sh
rm /usr/script/plugin3.sh
rm /usr/script/plugin4.sh
rm /usr/script/plugin5.sh
rm /usr/script/plugin6.sh
rm /usr/script/plugin7.sh
rm /usr/script/plugin8.sh
rm /usr/script/plugin9.sh
rm /usr/script/plugin10.sh
rm /usr/script/plugin11.sh
rm /usr/script/plugin12.sh
rm /usr/script/plugin13.sh
rm /usr/script/plugin14.sh
rm /usr/script/plugin15.sh
rm /usr/script/plugin16.sh
rm /usr/script/plugin17.sh
rm /usr/script/plugin18.sh
rm /usr/script/plugin19.sh
rm /usr/script/plugin20.sh
rm /usr/script/plugin21.sh
rm /usr/script/plugin22.sh
rm /usr/script/plugin23.sh
rm /usr/script/plugin24.sh
rm /usr/script/plugin25.sh
rm /usr/script/plugin26.sh
rm /usr/script/plugin27.sh
rm /usr/script/plugin28.sh
rm /usr/script/plugin29.sh
rm /usr/script/plugin30.sh
rm /usr/script/plugin31.sh
rm /usr/script/plugin32.sh
rm /usr/script/plugin33.sh
rm /usr/script/plugin34.sh
rm /usr/script/plugin35.sh
rm /usr/script/plugin36.sh
rm /usr/script/hledejM3U.sh
rm /usr/script/Normal.sh
rm /usr/script/Normalstart.sh
rm /usr/script/Lite.sh
rm /usr/script/Litestart.sh
rm /usr/script/ENG.sh
rm /usr/script/CZ.sh
rm /usr/script/film.sh
rm /usr/script/IPTV.sh
rm /usr/script/eporner.sh
rm /usr/script/CZSKfilmR.sh
rm /usr/script/po.sh
rm /usr/script/streamOK.sh
rm /usr/script/presunCFG.sh
rm /usr/script/presunCFG1.sh
rm /usr/script/ctecka.sh
rm /usr/script/ctecka1.sh
rm /usr/script/key.sh
rm /usr/script/aktivstart.sh
rm /usr/script/deaktivstart.sh
rm /usr/script/start.sh
rm /usr/script/start10.sh
rm /usr/script/start20.sh
rm /usr/script/start30.sh
rm /usr/script/start40.sh
rm /usr/script/start50.sh
rm /usr/script/znovune.sh
rm /usr/script/hod3.sh
rm /usr/script/sekvence.sh
rm /usr/script/CCcam1.sh
rm /usr/script/CCcam2.sh
rm /usr/script/CCcam3.sh
rm /usr/script/curlx.sh
rm /usr/script/curl1.sh
rm /usr/script/curl2.sh
rm /usr/script/curl3.sh
rm /usr/script/curl4.sh
rm /usr/script/curl5.sh
rm /usr/script/lang1.sh
rm /usr/script/lang2.sh
rm /usr/script/lang3.sh
rm /usr/script/lang4.sh
rm /usr/script/lang5.sh
rm /usr/script/lang6.sh
rm /usr/script/lang7.sh
rm /usr/script/lang8.sh
rm /usr/script/conv.sh
rm /usr/script/conv1.sh
rm /usr/script/conv2.sh
rm /usr/script/Gcam.sh
rm /usr/script/GcamDEB.sh
rm /usr/script/Oscam.sh
rm /usr/script/OscamDEB.sh
rm /usr/script/OscamSUPER.sh
rm /usr/script/OscamSUPERarm.sh
rm /usr/script/OscamSUPERmips.sh
rm /usr/script/Ncam.sh
rm /usr/script/NcamDEB.sh
rm /usr/script/Ncam2.sh
rm /usr/script/NcamDEB2.sh
rm /usr/script/velikost.sh
rm /usr/script/podekovani.sh
rm /usr/script/killCAM.sh
rm /usr/script/amateurCONV.sh
rm /usr/script/amateurCONVx.sh
rm /usr/script/asianCONV.sh
rm /usr/script/asianCONVx.sh
rm /usr/script/assCONV.sh
rm /usr/script/assCONVx.sh
rm /usr/script/blackCONV.sh
rm /usr/script/blackCONVx.sh
rm /usr/script/dickCONV.sh
rm /usr/script/dickCONVx.sh
rm /usr/script/lesbCONV.sh
rm /usr/script/lesbCONVx.sh
rm /usr/script/teenCONV.sh
rm /usr/script/teenCONVx.sh
rm /usr/script/titsCONV.sh
rm /usr/script/titsCONVx.sh
rm /usr/script/BlackedCONV.sh
rm /usr/script/BlackedCONVx.sh
rm /usr/script/BlackedRAWCONV.sh
rm /usr/script/BlackedRAWCONVx.sh
rm /usr/script/castingcouchCONV.sh
rm /usr/script/castingcouchCONVx.sh
rm /usr/script/TeensLoveHugeCONV.sh
rm /usr/script/TeensLoveHugeCONVx.sh
rm /usr/script/BlackAmbushCONV.sh
rm /usr/script/BlackAmbushCONVx.sh
rm /usr/script/openpanel.xml >>/dev/null 2>&1 </dev/null &
rm /usr/script/restart005jon.sh >>/dev/null 2>&1 </dev/null &
rm /usr/script/najdiCFG.sh >>/dev/null 2>&1 </dev/null &
rm /usr/script/IPTV/AfghanistanCONV.sh
rm /usr/script/IPTV/AlbaniaCONV.sh
rm /usr/script/IPTV/AlgeriaCONV.sh
rm /usr/script/IPTV/AndorraCONV.sh
rm /usr/script/IPTV/AngolaCONV.sh
rm /usr/script/IPTV/ArgentinaCONV.sh
rm /usr/script/IPTV/ArmeniaCONV.sh
rm /usr/script/IPTV/ArubaCONV.sh
rm /usr/script/IPTV/AustraliaCONV.sh
rm /usr/script/IPTV/AustriaCONV.sh
rm /usr/script/IPTV/AzerbaijanCONV.sh
rm /usr/script/IPTV/BahrainCONV.sh
rm /usr/script/IPTV/BangladeshCONV.sh
rm /usr/script/IPTV/BarbadosCONV.sh
rm /usr/script/IPTV/BelarusCONV.sh
rm /usr/script/IPTV/BelgiumCONV.sh
rm /usr/script/IPTV/BoliviaCONV.sh
rm /usr/script/IPTV/BosniaAndHerzegovinaCONV.sh
rm /usr/script/IPTV/BrazilCONV.sh
rm /usr/script/IPTV/BruneiCONV.sh
rm /usr/script/IPTV/BulgariaCONV.sh
rm /usr/script/IPTV/BurkinaFasoCONV.sh
rm /usr/script/IPTV/CambodiaCONV.sh
rm /usr/script/IPTV/CameroonCONV.sh
rm /usr/script/IPTV/CanadaCONV.sh
rm /usr/script/IPTV/ChileCONV.sh
rm /usr/script/IPTV/ChinaCONV.sh
rm /usr/script/IPTV/ColombiaCONV.sh
rm /usr/script/IPTV/CostaRicaCONV.sh
rm /usr/script/IPTV/CroatiaCONV.sh
rm /usr/script/IPTV/CuracaoCONV.sh
rm /usr/script/IPTV/CyprusCONV.sh
rm /usr/script/IPTV/CzechRepublicCONV.sh
rm /usr/script/IPTV/DemocraticRepublicOFtheCongoCONV.sh
rm /usr/script/IPTV/DenmarkCONV.sh
rm /usr/script/IPTV/DominicanRepublicCONV.sh
rm /usr/script/IPTV/EcuadorCONV.sh
rm /usr/script/IPTV/EgyptCONV.sh
rm /usr/script/IPTV/ElSalvadorCONV.sh
rm /usr/script/IPTV/EquatorialGuineaCONV.sh
rm /usr/script/IPTV/EstoniaCONV.sh
rm /usr/script/IPTV/EthiopiaCONV.sh
rm /usr/script/IPTV/FaroeIslandsCONV.sh
rm /usr/script/IPTV/FijiCONV.sh
rm /usr/script/IPTV/FinlandCONV.sh
rm /usr/script/IPTV/FranceCONV.sh
rm /usr/script/IPTV/GambiaCONV.sh
rm /usr/script/IPTV/GeorgiaCONV.sh
rm /usr/script/IPTV/GermanyCONV.sh
rm /usr/script/IPTV/GhanaCONV.sh
rm /usr/script/IPTV/GreeceCONV.sh
rm /usr/script/IPTV/GuadeloupeCONV.sh
rm /usr/script/IPTV/GuyanaCONV.sh
rm /usr/script/IPTV/HaitiCONV.sh
rm /usr/script/IPTV/HondurasCONV.sh
rm /usr/script/IPTV/HongKongCONV.sh
rm /usr/script/IPTV/HungaryCONV.sh
rm /usr/script/IPTV/IcelandCONV.sh
rm /usr/script/IPTV/IndiaCONV.sh
rm /usr/script/IPTV/IndonesiaCONV.sh
rm /usr/script/IPTV/InternationalCONV.sh
rm /usr/script/IPTV/IranCONV.sh
rm /usr/script/IPTV/IraqCONV.sh
rm /usr/script/IPTV/IrelandCONV.sh
rm /usr/script/IPTV/IsraelCONV.sh
rm /usr/script/IPTV/ItalyCONV.sh
rm /usr/script/IPTV/IvoryCoastCONV.sh
rm /usr/script/IPTV/JamaicaCONV.sh
rm /usr/script/IPTV/JapanCONV.sh
rm /usr/script/IPTV/JordanCONV.sh
rm /usr/script/IPTV/KazakhstanCONV.sh
rm /usr/script/IPTV/KenyaCONV.sh
rm /usr/script/IPTV/KosovoCONV.sh
rm /usr/script/IPTV/KuwaitCONV.sh
rm /usr/script/IPTV/KyrgyzstanCONV.sh
rm /usr/script/IPTV/LaosCONV.sh
rm /usr/script/IPTV/LatviaCONV.sh
rm /usr/script/IPTV/LebanonCONV.sh
rm /usr/script/IPTV/LibyaCONV.sh
rm /usr/script/IPTV/LiechtensteinCONV.sh
rm /usr/script/IPTV/LithuaniaCONV.sh
rm /usr/script/IPTV/LuxembourgCONV.sh
rm /usr/script/IPTV/MacauCONV.sh
rm /usr/script/IPTV/MalaysiaCONV.sh
rm /usr/script/IPTV/MexicoCONV.sh
rm /usr/script/IPTV/MoldovaCONV.sh
rm /usr/script/IPTV/MongoliaCONV.sh
rm /usr/script/IPTV/MontenegroCONV.sh
rm /usr/script/IPTV/MoroccoCONV.sh
rm /usr/script/IPTV/MozambiqueCONV.sh
rm /usr/script/IPTV/MyanmarCONV.sh
rm /usr/script/IPTV/NepalCONV.sh
rm /usr/script/IPTV/NetherlandsCONV.sh
rm /usr/script/IPTV/NewZealandCONV.sh
rm /usr/script/IPTV/NicaraguaCONV.sh
rm /usr/script/IPTV/NigeriaCONV.sh
rm /usr/script/IPTV/NorthKoreaCONV.sh
rm /usr/script/IPTV/NorthMacedoniaCONV.sh
rm /usr/script/IPTV/NorwayCONV.sh
rm /usr/script/IPTV/OmanCONV.sh
rm /usr/script/IPTV/PakistanCONV.sh
rm /usr/script/IPTV/PalestineCONV.sh
rm /usr/script/IPTV/PanamaCONV.sh
rm /usr/script/IPTV/ParaguayCONV.sh
rm /usr/script/IPTV/PeruCONV.sh
rm /usr/script/IPTV/PhilippinesCONV.sh
rm /usr/script/IPTV/PolandCONV.sh
rm /usr/script/IPTV/PortugalCONV.sh
rm /usr/script/IPTV/PuertoRicoCONV.sh
rm /usr/script/IPTV/QatarCONV.sh
rm /usr/script/IPTV/RomaniaCONV.sh
rm /usr/script/IPTV/RussiaCONV.sh
rm /usr/script/IPTV/RwandaCONV.sh
rm /usr/script/IPTV/SaudiArabiaCONV.sh
rm /usr/script/IPTV/SerbiaCONV.sh
rm /usr/script/IPTV/SingaporeCONV.sh
rm /usr/script/IPTV/SlovakiaCONV.sh
rm /usr/script/IPTV/SloveniaCONV.sh
rm /usr/script/IPTV/SouthKoreaCONV.sh
rm /usr/script/IPTV/SpainCONV.sh
rm /usr/script/IPTV/SriLankaCONV.sh
rm /usr/script/IPTV/SwedenCONV.sh
rm /usr/script/IPTV/SwitzerlandCONV.sh
rm /usr/script/IPTV/SyriaCONV.sh
rm /usr/script/IPTV/TaiwanCONV.sh
rm /usr/script/IPTV/TajikistanCONV.sh
rm /usr/script/IPTV/TanzaniaCONV.sh
rm /usr/script/IPTV/ThailandCONV.sh
rm /usr/script/IPTV/TrinidadANDTobagoCONV.sh
rm /usr/script/IPTV/TunisiaCONV.sh
rm /usr/script/IPTV/TurkeyCONV.sh
rm /usr/script/IPTV/TurkmenistanCONV.sh
rm /usr/script/IPTV/UgandaCONV.sh
rm /usr/script/IPTV/UkraineCONV.sh
rm /usr/script/IPTV/UnitedArabEmiratesCONV.sh
rm /usr/script/IPTV/UnitedKingdomCONV.sh
rm /usr/script/IPTV/UnitedStatesCONV.sh
rm /usr/script/IPTV/UruguayCONV.sh
rm /usr/script/IPTV/VietnamCONV.sh
rm /usr/script/IPTV/YemenCONV.sh

rm -rf /etc/panel
rm -rf /etc/CZ
rm -rf /etc/ENG
rm -rf /test
rm -rf /XXX
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/OpenPanel
rm -rf /usr/lib/enigma2/python/Screens/TextOut.py
rm -rf /usr/share/enigma2/OpenPanel
rm -rf /etc/plugins.xml
rm -rf /etc/openpanel.xml
rm -rf /usr/script/Del_Downloader.sh
opkg remove cfg - Zoom

killall -9 enigma2

exit 0
